### PR TITLE
Update for non uniform axes support

### PR DESCRIPTION
**Pull request by jlaehne**
Update to reflect availability of non uniform axes in hyperspy v1.7.0 and lumispy v0.2

- add explicit dependencies in environment.yaml so that binder is rebuilt in case the dependencies are updated
- change the documentation relating to energy conversion with the non uniform axes support now available
- update sample data file to new hyperspy version

### CODE REVIEW

**Comment by jlaehne** [comment]
@jordiferrero can you give me write access to this repository?

**Comment by jlaehne** [comment]
@ericpre any idea why the `binder_on_pr.yaml` action was not run? It is the same code as in `hyperspy-demos`. Does the package admin have to set up something in general for actions to run?

**Comment by ericpre** [comment]
Do the actions need to be activate for this repository?

**Comment by jlaehne** [comment]
> Do the actions need to be activate for this repository?

The directory was named `workflow` instead of `workflows`.

**Pull request merged**
